config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  devise_for :users

  root 'static_pages#home'

  resources :user do
    resources :posts do
      resources :comments
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true, length: { in: 1..255 }

  default_scope { order('created_at DESC') }

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { in: 1..255 }
  validates :content, presence: true, length: { in: 1..255 }

  default_scope { order('created_at DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:success] = "Commented!"
    else
      flash[:error] = @comment.errors.full_messages.to_sentence
    end

    redirect_to user_post_path(@comment.user, @comment.post)
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :find_post, only: [:edit, :update, :destroy]
  before_action :find_any_post, only: :show

  respond_to :html

  def index
    @posts = current_user.posts.paginate(:page => params[:page])
  end

  def show
    @comments = @post.comments.paginate(:page => params[:page])
  end

  def new
    @post = current_user.posts.new
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post was edited!"
      redirect_to user_post_path(current_user, @post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post was destroyed"

    redirect_to user_posts_path(current_user)
  end

  private
    def find_post
      @post = current_user.posts.find(params[:id])
    end

    def find_any_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content, :title)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.all.paginate(:page => params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.slim
.span8
  p
    = comment.content
  div
    span.badge.badge-primary commented #{comment.created_at.try(:strftime, '%c')}
    .pull-right
      = comment.user.try(:email)
  hr/

app/views/comments/_comments.html.slim
.col-sm-9.col-sm-offset-3
  h4 Comments

  - if current_user
    hr/
    = render 'comments/form'

  hr/
  = will_paginate @comments
  - @comments.each do |comment|
    = render 'comments/comment', comment: comment

app/views/comments/_form.html.slim
= simple_form_for [current_user, @post, @post.comments.new] do |f|
  = f.error_notification

  .form-inputs
    = f.input :content, label: false, placeholder: 'Please enter your comment here'
    = f.input :post_id, as: :hidden

  .form-actions
    .btn-group
      = f.submit 'Add comment', class: 'btn btn-primary'

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Content:
  = @comment.content
p
  strong User:
  = @comment.user_id
p
  strong Post:
  = @comment.post_id

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Salaeva"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          .navbar-brand
            = link_to "Main", root_path
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav.pull-right
              - if current_user
                li= link_to current_user.email, user_posts_path(current_user) if current_user
                li= link_to 'EXIT', destroy_user_session_path, method: :delete
              - else
                li= link_to 'Sign In', new_user_session_path
                li= link_to 'Sign Up', new_user_registration_path

    .container
      .row
        .col-sm-12
          = bootstrap_flash
          = yield

app/views/posts/_form.html.slim
= simple_form_for [current_user, @post] do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :content

  .form-actions
    .btn-group
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to 'Back', user_posts_path(current_user), class: 'btn btn-danger'

app/views/posts/_post.html.slim
.span8
  h3
    = link_to post.title, user_post_path(post.user, post)
  p
    = post.content
  div
    span.badge.badge-primary Posted #{post.created_at.strftime('%c')}
    .pull-right
      = post.user.email
  hr/

app/views/posts/edit.html.slim
h1 Editing post

= render 'form'

app/views/posts/index.html.slim
.pull-right
  = link_to 'New Post', new_user_post_path(current_user), class: 'btn btn-primary'
h1 Listing posts

hr/
= will_paginate @posts
- @posts.each do |post|
  = render 'post', post: post

app/views/posts/new.html.slim
h1 New post

= render 'form'

app/views/posts/show.html.slim
p#notice = notice

= render 'post', post: @post

- if @post.user == current_user
  = render 'shared/edit_delete_btn'
= render 'comments/comments', comments: @comments

app/views/shared/_edit_delete_btn.html.slim
.btn-group
  = link_to 'Edit', edit_user_post_path(current_user, @post), class: 'btn btn-warning'
  = link_to 'Destroy', user_post_path(current_user, @post), method: :delete, class: 'btn btn-danger'

app/views/static_pages/home.html.slim
h1 Listing posts

hr/
= will_paginate @posts
- @posts.each do |post|
  = render 'posts/post', post: post

br